name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OninOneProxy Version
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker
        - Source (npm)
        - Source (bun)
    validations:
      required: true
